export const AppString = {
  GREETING: "greeting",
  PLAYER: "player",
  DECREMENT_SCORE: "decrementScore",
  RESET_SCORE: "resetScore",
  DELETE_PLAYER: "deletePlayer",
  CLOSE_WINDOW: "closeWindow",
  DELETE_PLAYER_ALERT_TITLE: "deletePlayerAlertTitle",
  DELETE_PLAYER_ALERT_MSG: "deletePlayerAlertMsg",
  ALERT_YES: "alertYes",
  ALERT_NO: "alertNo",
  NEW_GAME_ALERT_TITLE: "newGameAlertTitle",
  NEW_GAME_ALERT_MSG: "newGameAlertMsg",
  HELP_MENU_TITLE: "helpMenuTitle",
  HELP_MENU_WHATS_THIS_Q: "helpMenuWhatIsThisQ",
  HELP_MENU_WHATS_THIS_A: "helpMenuWhatIsThisA",
  HELP_MENU_WHAT_DO_YOU_MEAN_Q: "helpMenuWhatDoYouMeanQ",
  HELP_MENU_WHAT_DO_YOU_MEAN_A: "helpMenuWhatDoYouMeanA",
  HELP_MENU_CLOSE: "helpMenuClose",
};
